In [3]:
import psycopg2

conn = psycopg2.connect(
    host="postgres",      # service name from docker-compose.yml, not localhost
    port=5432,
    dbname="mydatabase",         # whatever you set as POSTGRES_DB
    user="root",
    password="root"
)

cur = conn.cursor()
cur.execute("SELECT version();")
print(cur.fetchone())

cur.close()
conn.close()

('PostgreSQL 18.4 (Debian 18.4-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit',)

In [6]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("postgresql://root:root@postgres:5432/mydatabase")

df = pd.read_sql("SELECT version();", engine)
df

                                             version
0  PostgreSQL 18.4 (Debian 18.4-1.pgdg13+1) on x8...

In [7]:
import requests

url = "https://opensky-network.org/api/states/all"
response = requests.get(url)
data = response.json()

print(data.keys())
print(len(data['states']), "aircraft currently tracked")
data['states'][0]  # look at one raw record

dict_keys(['time', 'states'])
7982 aircraft currently tracked

['801638',
 'AXB2782 ',
 'India',
 None,
 1785892540,
 None,
 None,
 None,
 False,
 236.78,
 184.24,
 0,
 None,
 None,
 None,
 False,
 0]

In [8]:
import pandas as pd

columns = [
    "icao24", "callsign", "origin_country", "time_position", 
    "last_contact", "longitude", "latitude", "baro_altitude", 
    "on_ground", "velocity", "true_track", "vertical_rate", 
    "sensors", "geo_altitude", "squawk", "spi", "position_source"
]

df = pd.DataFrame(data['states'], columns=columns)
df['callsign'] = df['callsign'].str.strip()
df = df.drop(columns=['sensors'])   # <-- new line, matches table schema

df.to_sql('flight_positions', engine, if_exists='append', index=False)

df.head()

,icao24,callsign,origin_country,time_position,last_contact,longitude,latitude,baro_altitude,on_ground,velocity,true_track,vertical_rate,geo_altitude,squawk,spi,position_source
0,801638,AXB2782,India,NaN,1785892540,NaN,NaN,NaN,False,236.78,184.24,0.00,NaN,None,False,0
1,ac494e,CMD3,United States,1.785893e+09,1785892542,-122.2712,40.4714,579.12,False,73.19,317.56,-2.28,518.16,None,False,0
2,aa9321,UAL97,United States,1.785892e+09,1785892349,158.5085,-24.9184,10058.40,False,322.80,74.28,0.00,10439.40,None,False,0
3,801640,AIC2249,India,1.785892e+09,1785892320,54.6090,22.0766,10972.80,False,251.04,264.83,0.00,11734.80,4050,False,0
4,ab6fdd,AAL1425,United States,1.785893e+09,1785892542,-93.6591,33.7301,11277.60,False,239.82,70.71,0.00,11963.40,2212,False,0

In [ ]:
from sqlalchemy import text

create_table_sql = """
CREATE TABLE IF NOT EXISTS flight_positions (
    id SERIAL PRIMARY KEY,
    icao24 VARCHAR(10),
    callsign VARCHAR(20),
    origin_country VARCHAR(100),
    time_position BIGINT,
    last_contact BIGINT,
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    baro_altitude DOUBLE PRECISION,
    on_ground BOOLEAN,
    velocity DOUBLE PRECISION,
    true_track DOUBLE PRECISION,
    vertical_rate DOUBLE PRECISION,
    geo_altitude DOUBLE PRECISION,
    squawk VARCHAR(10),
    spi BOOLEAN,
    position_source INTEGER,
    ingested_at TIMESTAMP DEFAULT NOW()
);
"""

with engine.connect() as connection:
    connection.execute(text(create_table_sql))
    connection.commit()

In [9]:
pd.read_sql("SELECT COUNT(*) FROM flight_positions;", engine)

   count
0  41980

In [ ]:
pd.read_sql("SELECT * FROM flight_positions ORDER BY ingested_at DESC LIMIT 5;", engine)