In [3]:
!pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: sqlalchemy in /opt/conda/lib/python3.11/site-packages (2.0.22)
Requirement already satisfied: typing-extensions>=4.2.0 in /opt/conda/lib/python3.11/site-packages (from sqlalchemy) (4.8.0)
Requirement already satisfied: greenlet!=0.4.17 in /opt/conda/lib/python3.11/site-packages (from sqlalchemy) (3.0.0)
Downloading psycopg2_binary-2.9.12-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 1.2 MB/s eta 0:00:0000:0100:010m
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12

In [5]:
import psycopg2

conn = psycopg2.connect(
    host="postgres",      # service name from docker-compose.yml, not localhost
    port=5432,
    dbname="mydatabase",         # whatever you set as POSTGRES_DB
    user="root",
    password="root"
)

cur = conn.cursor()
cur.execute("SELECT version();")
print(cur.fetchone())

cur.close()
conn.close()

('PostgreSQL 18.4 (Debian 18.4-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit',)

In [7]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("postgresql://root:root@postgres:5432/mydatabase")

df = pd.read_sql("SELECT version();", engine)
df

                                             version
0  PostgreSQL 18.4 (Debian 18.4-1.pgdg13+1) on x8...

In [10]:
import requests

url = "https://opensky-network.org/api/states/all"
response = requests.get(url)
data = response.json()

print(data.keys())
print(len(data['states']), "aircraft currently tracked")
data['states'][0]  # look at one raw record

dict_keys(['time', 'states'])
8291 aircraft currently tracked

['801638',
 'AXB2782 ',
 'India',
 1785804953,
 1785805996,
 88.5519,
 20.8657,
 8831.58,
 False,
 230.39,
 169.97,
 0.33,
 None,
 9410.7,
 None,
 False,
 0]

In [18]:
import pandas as pd

columns = [
    "icao24", "callsign", "origin_country", "time_position", 
    "last_contact", "longitude", "latitude", "baro_altitude", 
    "on_ground", "velocity", "true_track", "vertical_rate", 
    "sensors", "geo_altitude", "squawk", "spi", "position_source"
]

df = pd.DataFrame(data['states'], columns=columns)
df['callsign'] = df['callsign'].str.strip()
df = df.drop(columns=['sensors'])   # <-- new line, matches table schema

df.to_sql('flight_positions', engine, if_exists='append', index=False)

df.head()

,icao24,callsign,origin_country,time_position,last_contact,longitude,latitude,baro_altitude,on_ground,velocity,true_track,vertical_rate,geo_altitude,squawk,spi,position_source
0,801638,AXB2782,India,1.785805e+09,1785805996,88.5519,20.8657,8831.58,False,230.39,169.97,0.33,9410.70,None,False,0
1,aa9321,UAL506,United States,1.785806e+09,1785806006,-120.4000,44.4385,11277.60,False,245.55,197.18,0.00,11803.38,None,False,0
2,a5953a,TRF559,United States,1.785806e+09,1785806006,-95.7315,30.7755,922.02,False,47.35,271.87,0.65,922.02,None,False,0
3,ab296f,,United States,NaN,1785805998,NaN,NaN,NaN,False,27.85,258.27,4.23,NaN,None,False,0
4,8744f6,ANA54,Japan,1.785806e+09,1785805999,141.2085,39.6638,12192.00,False,266.26,194.09,0.33,13098.78,None,False,0

In [15]:
from sqlalchemy import text

create_table_sql = """
CREATE TABLE IF NOT EXISTS flight_positions (
    id SERIAL PRIMARY KEY,
    icao24 VARCHAR(10),
    callsign VARCHAR(20),
    origin_country VARCHAR(100),
    time_position BIGINT,
    last_contact BIGINT,
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    baro_altitude DOUBLE PRECISION,
    on_ground BOOLEAN,
    velocity DOUBLE PRECISION,
    true_track DOUBLE PRECISION,
    vertical_rate DOUBLE PRECISION,
    geo_altitude DOUBLE PRECISION,
    squawk VARCHAR(10),
    spi BOOLEAN,
    position_source INTEGER,
    ingested_at TIMESTAMP DEFAULT NOW()
);
"""

with engine.connect() as connection:
    connection.execute(text(create_table_sql))
    connection.commit()

In [19]:
pd.read_sql("SELECT COUNT(*) FROM flight_positions;", engine)

   count
0  16582

In [20]:
pd.read_sql("SELECT * FROM flight_positions ORDER BY ingested_at DESC LIMIT 5;", engine)

,id,icao24,callsign,origin_country,time_position,last_contact,longitude,latitude,baro_altitude,on_ground,velocity,true_track,vertical_rate,geo_altitude,squawk,spi,position_source,ingested_at
0,8294,a5953a,TRF559,United States,1.785806e+09,1785806006,-95.7315,30.7755,922.02,False,47.35,271.87,0.65,922.02,None,False,0,2026-08-04 01:50:12.274903
1,8295,ab296f,,United States,NaN,1785805998,NaN,NaN,NaN,False,27.85,258.27,4.23,NaN,None,False,0,2026-08-04 01:50:12.274903
2,8292,801638,AXB2782,India,1.785805e+09,1785805996,88.5519,20.8657,8831.58,False,230.39,169.97,0.33,9410.70,None,False,0,2026-08-04 01:50:12.274903
3,8293,aa9321,UAL506,United States,1.785806e+09,1785806006,-120.4000,44.4385,11277.60,False,245.55,197.18,0.00,11803.38,None,False,0,2026-08-04 01:50:12.274903
4,8296,8744f6,ANA54,Japan,1.785806e+09,1785805999,141.2085,39.6638,12192.00,False,266.26,194.09,0.33,13098.78,None,False,0,2026-08-04 01:50:12.274903